"""
Deterministic Security Alert Correlation Engine.

Processes raw security alerts, performs cryptographic fingerprinting for deduplication,
evaluates deterministic correlation rules, calculates aggregated risk scores, and groups
related alerts into Incident candidates with entity graph visualization networks.
"""

import math
import hashlib
import uuid
from datetime import datetime, timezone
from typing import List, Dict, Any, Optional, Tuple, Set
from pydantic import BaseModel, Field

from app.models.alert import Alert, AlertSeverity
from app.models.incident import IncidentSeverity, IncidentPriority, IncidentCategory
from app.correlation.rules import CorrelationRule, get_default_correlation_rules
from app.correlation.graph import CorrelationGraph


class AlertDeduplicationRecord(BaseModel):
    """Result payload from alert deduplication evaluation."""

    unique_alerts: List[Any] = Field(default_factory=list)
    duplicate_count: int = Field(0)
    fingerprints: Dict[str, int] = Field(default_factory=dict)


class CorrelatedIncidentCandidate(BaseModel):
    """Candidate correlated incident generated by deterministic rule matching."""

    candidate_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    title: str = Field(...)
    description: str = Field(...)
    category: IncidentCategory = Field(IncidentCategory.OTHER)
    severity: IncidentSeverity = Field(IncidentSeverity.MEDIUM)
    priority: IncidentPriority = Field(IncidentPriority.P3)
    risk_score: float = Field(50.0)
    confidence_score: float = Field(80.0)
    alert_ids: List[uuid.UUID] = Field(default_factory=list)
    matched_rule_id: Optional[str] = Field(None)
    matched_rule_name: Optional[str] = Field(None)
    graph: CorrelationGraph = Field(default_factory=CorrelationGraph)


class CorrelationEngine:
    """Enterprise Deterministic Correlation Engine."""

    def __init__(self, rules: Optional[List[CorrelationRule]] = None):
        self.rules = rules if rules is not None else get_default_correlation_rules()

    @staticmethod
    def get_alert_attr(alert: Any, attr_name: str, default_val: Any = None) -> Any:
        """Helper to extract property from either Pydantic/SQLAlchemy model or dictionary."""
        if isinstance(alert, dict):
            return alert.get(attr_name, default_val)
        return getattr(alert, attr_name, default_val)

    @classmethod
    def calculate_alert_fingerprint(cls, alert: Any) -> str:
        """Calculate a deterministic hash fingerprint for an alert entity or dictionary."""
        source = str(cls.get_alert_attr(alert, "source", "") or "")
        title = str(cls.get_alert_attr(alert, "title", "") or "")

        raw = cls.get_alert_attr(alert, "raw_payload", {}) or {}
        host = str(raw.get("hostname") or raw.get("host") or "")
        user = str(raw.get("username") or raw.get("user") or "")

        iocs = cls.get_alert_attr(alert, "iocs", {}) or {}
        ip = str(iocs.get("ip") or iocs.get("source_ip") or "")

        fingerprint_str = f"{source}:{title}:{host}:{user}:{ip}".lower()
        return hashlib.sha256(fingerprint_str.encode("utf-8")).hexdigest()

    def deduplicate_alerts(self, alerts: List[Any]) -> AlertDeduplicationRecord:
        """Filter out duplicate alerts based on fingerprint hash."""
        seen: Dict[str, int] = {}
        unique_alerts: List[Any] = []
        duplicates = 0

        for alert in alerts:
            fp = self.calculate_alert_fingerprint(alert)
            if fp in seen:
                seen[fp] += 1
                duplicates += 1
            else:
                seen[fp] = 1
                unique_alerts.append(alert)

        return AlertDeduplicationRecord(
            unique_alerts=unique_alerts,
            duplicate_count=duplicates,
            fingerprints=seen,
        )

    @classmethod
    def calculate_aggregated_risk_score(cls, alerts: List[Any], rule_weight: float = 1.0) -> float:
        """
        Calculate deterministic risk score for an alert group.
        
        Formula:
          Base = max(alert_risk_scores)
          Volume Bonus = ln(count + 1) * 10
          Calculated = (Base + Volume Bonus) * Rule Multiplier
          Capped between 0.0 and 100.0.
        """
        if not alerts:
            return 50.0

        risks = []
        for a in alerts:
            val = cls.get_alert_attr(a, "risk_score", 50.0)
            risks.append(float(val if val is not None else 50.0))

        base_risk = max(risks)
        volume_bonus = math.log(len(alerts) + 1) * 10.0
        
        calculated_risk = (base_risk + volume_bonus) * rule_weight
        return max(0.0, min(100.0, round(calculated_risk, 1)))

    @staticmethod
    def map_severity_from_risk(risk_score: float) -> Tuple[IncidentSeverity, IncidentPriority]:
        """Map numerical risk score to Incident Severity and Triage Priority."""
        if risk_score >= 85.0:
            return IncidentSeverity.CRITICAL, IncidentPriority.P1
        elif risk_score >= 70.0:
            return IncidentSeverity.HIGH, IncidentPriority.P2
        elif risk_score >= 40.0:
            return IncidentSeverity.MEDIUM, IncidentPriority.P3
        else:
            return IncidentSeverity.LOW, IncidentPriority.P4

    @classmethod
    def extract_field_value(cls, alert: Any, field_name: str) -> Optional[str]:
        """Extract value of specified attribute or payload property from alert."""
        direct_val = cls.get_alert_attr(alert, field_name)
        if direct_val is not None and not isinstance(direct_val, (dict, list)):
            return str(direct_val)

        raw = cls.get_alert_attr(alert, "raw_payload", {}) or {}
        if field_name in raw and raw[field_name] is not None:
            return str(raw[field_name])

        iocs = cls.get_alert_attr(alert, "iocs", {}) or {}
        if field_name in iocs and iocs[field_name] is not None:
            return str(iocs[field_name])

        return None

    def evaluate(self, alerts: List[Any]) -> List[CorrelatedIncidentCandidate]:
        """Evaluate deterministic rules over alert collection and produce Incident Candidates."""
        if not alerts:
            return []

        # Deduplicate first
        dedup = self.deduplicate_alerts(alerts)
        active_alerts = dedup.unique_alerts
        candidates: List[CorrelatedIncidentCandidate] = []
        processed_alert_ids: Set[str] = set()

        enabled_rules = [r for r in self.rules if r.enabled]

        for rule in enabled_rules:
            # Group alerts matching rule criteria
            groups: Dict[str, List[Any]] = {}

            for alert in active_alerts:
                alert_id_str = str(getattr(alert, "id", alert.get("id") if isinstance(alert, dict) else ""))
                if alert_id_str in processed_alert_ids:
                    continue

                # Field grouping key
                group_keys = []
                for field in rule.group_by_fields:
                    val = self.extract_field_value(alert, field)
                    if val:
                        group_keys.append(f"{field}:{val}")

                group_key_str = "|".join(sorted(group_keys)) if group_keys else "global_rule_cluster"

                if group_key_str not in groups:
                    groups[group_key_str] = []
                groups[group_key_str].append(alert)

            # Evaluate each group against rule thresholds
            for g_key, group_alerts in groups.items():
                if len(group_alerts) >= rule.min_alerts:
                    # Collect alert UUIDs
                    uids = []
                    for a in group_alerts:
                        raw_id = getattr(a, "id", a.get("id") if isinstance(a, dict) else None)
                        if isinstance(raw_id, uuid.UUID):
                            uids.append(raw_id)
                        elif isinstance(raw_id, str) and raw_id:
                            try:
                                uids.append(uuid.UUID(raw_id))
                            except ValueError:
                                pass
                        processed_alert_ids.add(str(raw_id))

                    risk_score = self.calculate_aggregated_risk_score(group_alerts, rule.weight)
                    severity, priority = self.map_severity_from_risk(risk_score)

                    first_title = getattr(group_alerts[0], "title", "Security Alert")
                    inc_title = f"Correlated Incident: {rule.name} ({len(group_alerts)} Alerts)"
                    inc_desc = (
                        f"Deterministic correlation rule '{rule.name}' grouped {len(group_alerts)} security alerts "
                        f"matching entity criteria '{g_key}'."
                    )

                    # Build graph
                    graph = CorrelationGraph()
                    graph.build_from_alerts(group_alerts)

                    candidate = CorrelatedIncidentCandidate(
                        title=inc_title,
                        description=inc_desc,
                        category=IncidentCategory.MALWARE if "malware" in inc_title.lower() else IncidentCategory.OTHER,
                        severity=severity,
                        priority=priority,
                        risk_score=risk_score,
                        confidence_score=90.0,
                        alert_ids=uids,
                        matched_rule_id=rule.id,
                        matched_rule_name=rule.name,
                        graph=graph,
                    )
                    candidates.append(candidate)

        return candidates
